version: "3"

services:
   mc-address-eureka-server:
      build: .
      image: mc-address-eureka-server
      ports:
         - "8761:8761"
      environment:
         eureka.instance.hostname: mc-address-eureka-server
         
   mc-customer-address:
      build: ../mc-customer-address
      image: mc-customer-address
      ports:
         - "8080:8080"
      environment:
         WAIT_HOSTS: mc-address-eureka-server:8761
         eureka.client.serviceUrl.defaultZone: http://mc-address-eureka-server:8761/eureka
         
   mc-zip-code-validator:
      build: ../mc-zip-code-validator
      image: mc-zip-code-validator
      ports:
         - "8081-8086:8081"
      environment:
         WAIT_HOSTS: mc-address-eureka-server:8761
         eureka.client.serviceUrl.defaultZone: http://mc-address-eureka-server:8761/eureka